apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: his-keycloak
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    ssl = off
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             0.0.0.0/0               md5
